language: python
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade numpy scipy pytest-cov codecov
- python setup.py install
script:
- python -m pytest -vv --cov=responsum/
- codecov --token=8737e56f-3b56-4abd-b678-acc8f7f0bb99
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: djlcDth/eUvkOt2o+TapH5cTajsO3Th/IPcxlBOCtWvPWPMv5TIpVRnJABBSfQBfK9Im+/1sxAoOqTcRvi3YArCHgYHcwHvKYSA34a9qakAcdAcWl0zYU6boKGACQK2O3KbPrbDLgghUIKf/uSu+Z84P3QR546xcocKHdgXCW0TUlQEchJ21zXGfXmOJv4T2+OEON1HlHsQx4WH7GobwzuE5fpLbi0tHQeq052BNZBOQXIkaVgQ7bUlM32fYVdWsbVBLEbe1j+nOS5n/E6v8XGlrQdr/FuTYETjcibzYDhiKRUuI7S8Ax8aEUeJP9iFzXzSgcnqCZ02JDjQuPAgM+8qFAYhz2F/n342kpB4aljYuEcltQ+GsUqP/wEy7Y52Nw5TUqn7vZwEQW3kwrDGOOR6+f9CSCzx7sS1jU10bUtS/BR+6y7xdd1djV5Y1etFGJwKAmWzNxKV+vSvBqAuB7xaYtA82/mFmU6hcPSlLKfd4Y/VuTRWznXye/ul+1Qhz2VWjjut6AvkFZsK4hHlrwKbyxsK49zvgMzTzlSZ7krurYtMbBHTxayIGlt+b6WUqYMZXdprPFNMPPQbv97708XfuOlAYewXcfve1717iSCW2Y3sEUsW02yBVdCdefr8McdN5gYxuUkcVTPKWmPRQbMBSzijJbWN3wVIxbCFHPkY=
  on:
    tags: true
  distributions: "sdist bdist_wheel" # Your distributions here
  skip_existing: true

