
# Config file for automatic testing at travis-ci.org

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
 
  - "3.6"
  - "3.7"
os:
  - linux
  - osx


install:
  - pip install --upgrade numpy scipy pytest-cov codecov
  - python setup.py install
script:
  - python -m pytest -vv --cov=responsum/
  - codecov --token=8737e56f-3b56-4abd-b678-acc8f7f0bb99









