
# Config file for automatic testing at travis-ci.org

language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
 
  - "3.6"
  - "3.7"
# os:
#   - linux
#   - osx


install:
  - pip install --upgrade numpy scipy pytest-cov codecov
  - python setup.py install
script:
  - python -m pytest -vv --cov=responsum/
#  - codecov --token=39cbd278-9065-488d-b323-b2b3dcc4ce1e









